server:
  port: 8080

service:
  message: API Gateway loaded from Github config repo

spring:
  # 1. ADDED REDIS CONFIGURATION FOR TRACKING THE LIMITS
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes: # Corrected from server.webflux.routes
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products,/api/v1/products/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Platform, microservices-pro
            # 2. ADDED RATE LIMITER FILTER FOR PRODUCT SERVICE
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory,/api/v1/inventory/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Platform, microservices-pro
            # 3. ADDED RATE LIMITER FILTER FOR INVENTORY SERVICE
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders,/api/v1/orders/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Platform, microservices-pro
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments,/api/v1/payments/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Platform, microservices-pro
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

gateway:
  public-routes:
    - method: POST
      path: /api/auth/login
    - method: POST
      path: /api/auth/register
    - method: GET
      path: /actuator/**
    - method: GET
      path: /api/v1/products/**


jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-jwt-authentication-123456}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway