server:
  port: 8080

service:
  message: API Gateway loaded from Github config repo

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/ecommerce-platform/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products,/api/v1/products/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: inventory-service-route
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/inventory,/api/v1/inventory/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders,/api/v1/orders/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: payment-service-route
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments,/api/v1/payments/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

gateway:
  public-routes:
    - method: POST
      path: /api/auth/login
    - method: POST
      path: /api/auth/register
    - method: GET
      path: /actuator/**
    - method: GET
      path: /api/v1/products/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus