management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
  endpoint:
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    INFO: INFO

service:
  message: Common config loaded from Github repository