management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreaker , circuitbreakerevents,
  endpoint:
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    root: INFO

service:
  message: Common config loaded from Github repository