server:
  port: 8082


spring: 
  kafka: 
    bootstrap-servers: localhost:9092 
  
    producer: 
      key-serializer: org.apache.kafka.common.serialization.StringSerializer 
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

service:
  message: Order service loaded from Github repository

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  retry:
    instances:
      paymentService:
        max-attempts: 3             # try 3 times total
        wait-duration: 500ms        # wait 500ms between attempts
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2  # 500ms → 1s → 2s
        retry-exceptions:
          - java.lang.RuntimeException   # only retry on these
        ignore-exceptions:
          - java.lang.IllegalArgumentException  # never retry on these
  bulkhead:
    instances:
      paymentService:
        max-concurrent-calls: 10    # max 10 simultaneous calls to Payment
        max-wait-duration: 0ms      # fail immediately if full

  timelimiter:
    instances:
      paymentService:
        timeout-duration: 2s         # fail if Payment takes > 2 seconds
        cancel-running-future: true  # cancel the thread on timeout

logging:
  level:
    io.github.resilience4j.retry: DEBUG