server:
  port: 8083

spring: 
  kafka: 
    bootstrap-servers: localhost:9092 
  
    producer: 
      key-serializer: ...StringSerializer 
      value-serializer: ...JsonSerializer 

    consumer: 
      group-id: ${spring.application.name} 
      key-deserializer: ...StringDeserializer 
      value-deserializer: ...JsonDeserializer 
      properties: 
        spring.json.trusted.packages: "com.raya.*" 
      auto-offset-reset: earliest
 


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  message: Payment service loaded from Github repository